export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const CHANGE_PASS_BEGIN = "CHANGE_PASS_BEGIN";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_ERROR = "CHANGE_PASS_ERROR";
